default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] { 'postgres' } %>
  user: <%= ENV['POSTGRES_USER'] { 'postgres' } %>
  password: <%= ENV['POSTGRES_PASSWORD'] { 'password' } %>

development:
  <<: *default
  database: simpleauth_development

test:
  <<: *default
  database: simpleauth_test

production:
  <<: *default
  database: simpleauth_production